version: "3.8"

services:
  db:
    image: postgres:15
    container_name: eventmanager_postgres
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./backend
    container_name: eventmanager_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eventdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    container_name: eventmanager_frontend
    ports:
      - "8082:80"
    depends_on:
      - app

volumes:
  db_data:
