logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/eventdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs

swagger-ui:
  path: /swagger-ui.html
  enabled: true
